common: &common
  adapter: postgresql
  encoding: utf8
  template: template0 # Required for UTF8 encoding

development:
  <<: *common
  database: booky_development

test:
  <<: *common
  database: booky_test